[project]
name = "assignments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.84.0",
    "dataclasses>=0.8",
    "dotenv>=0.9.9",
    "google>=3.0.0",
    "google-genai>=1.66.0",
    "huggingface-hub>=1.6.0",
    "langchain[anthropic,google-genai,openai]>=1.2.12",
    "langgraph>=1.1.1",
    "openai>=2.26.0",
    "typing>=3.10.0.0",
]
